
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

export const polishAIText = async (text: string): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `You are a text cleaning expert. I have text generated by an AI that contains Markdown formatting. 
      Please return the text with ALL markdown formatting removed (no bold, no italics, no bullet symbols, no header symbols). 
      IMPORTANT: Preserve all paragraph breaks, spacing, and the natural flow of the content. 
      Do not summarize. Do not change the wording. Just strip the formatting.
      
      Input text:
      ---
      ${text}
      ---`,
    });

    return response.text || text;
  } catch (error) {
    console.error("Gemini Polishing failed:", error);
    throw error;
  }
};
